### ISSUE TITLE
Please support ingress (and auth)

### ISSUE THREAD

**Issue by knobunc** [hassio-addons/addon-grafana#32]
# Problem/Motivation

Ingress support makes deploying the plugin far easier.

## Expected behavior

Have the option for Ingress and adding to the panel sidebar.

## Actual behavior

The options are not present yet.

**Comment by frenck** [comment]
Thank you for your request, unfortunately,  that is not possible with this add-on.

**Comment by knobunc** [comment]
What is missing that makes it impossible?

**Comment by frenck** [comment]
Multiple things. First of all, supporting both Ingress & Direct access would be difficult, since Grafana does not allow you to dynamically change the base URL is uses.
Secondly, the URL's are pretty hardcoded, which makes replacing using substitution filters nearly impossible.
Third, Grafana is aware of users, although Ingress is aware of the user, it does not provide information about the user to the service it addresses, hence, Grafana has no clue who you are.
